### ISSUE TITLE
Broken API Get "Driver"

### ISSUE THREAD

**Issue by CarsonStevens** [Geotab/mygeotab-python#16]
I'm trying to export the Driver list using the API client, but am getting an InvaliCastException:

```python
import mygeotab

client = mygeotab.API(username=username, password=password, database=database)
client.authenticate()

print(client.call('GetVersion')) # 8.0.2441
data = client.get('Driver')
```

MyGeotabException: InvalidCastException
Unable to cast object of type 'Geotab.Checkmate.Database.Bridge.UserBridge' to type 'Geotab.Database.IGetStore`1[Geotab.Checkmate.ObjectModel.Driver]'.
![image](https://user-images.githubusercontent.com/25759920/220795337-d6669478-47a3-4898-bd22-b64a870a3920.png)

**Comment by aaront** [comment]
Hi @CarsonStevens,

Drivers are users (with some added properties), and can be retrieved using the `userSearchType` property of the [UserSearch](https://geotab.github.io/sdk/software/api/reference/#UserSearch):

```python
data = client.get('User', userSearchType='Driver')
```

**Comment by CarsonStevens** [comment]
This fixed my problem. Thank you
