### ISSUE TITLE
Broken API Get "WorkTime"

### ISSUE THREAD

**Issue by CarsonStevens** [Geotab/mygeotab-python#17]
Trying to get the "WorkTime" Entities and the get method is throwing an error:
```python
import mygeotab

client = mygeotab.API(username=username, password=password, database=database)
client.authenticate()
print(client.call('GetVersion')) # 8.0.2441

data = client.get('WorkTime')
```

AttributeError: 'str' object has no attribute 'keys'
![image](https://user-images.githubusercontent.com/25759920/220796129-a8daf101-01bb-432f-9ed8-1dfbeb2a3111.png)

**Comment by aaront** [comment]
Hi @CarsonStevens,

This looks odd to be as it shouldn't be using `pandas` at all when using the code snippet you provided. Could you show more of this trace?

Thanks
