### ISSUE TITLE
Authentication with 'session_id' in the Credentials object raises 'ArgumentException'

### ISSUE THREAD

**Issue by nolan-sensorup** [Geotab/mygeotab-python#19]
When authenticating with a Credentials object that is given a `session_id` value and authenticating:

```python
credentials = Credentials(username=..., database=..., server=..., session_id=...)
client = API.from_credentials(credentials)
```

The following error is returned:
```python
{
    error: {
        code: -32000,
        data: {},
        errors: [
            {
                "message": "\"This method has been deprecated, and requires a custom code to be used. please use new methode 'ExtendSessionAsync' to extend your session.\"",
                "name": "'ArgumentException'",
            }
        ],
        message: "This method has been deprecated, and requires a custom code to be used. please use new methode 'ExtendSessionAsync' to extend your session.",
        name: "JSONRPCError",
    },
    id: -1,
    jsonrpc: "2.0",
    requestIndex: 0,
}
```

Details from GeoTab Community:
https://community.geotab.com/s/question/0D52J00009iEouYSAS/fail-to-authenticate-method-has-been-deprecated?language=en_US

`mygeotab` version: `0.8.8`

**Comment by aaront** [comment]
Hi @nolan-sensorup, I'll be taking a look at improvements, but as workaround when using the `client` after assigning it with `API.from_credentials(credentials)`, **you don't have to call `client.authenticate()`**.

If at this point you do want to extend your session, you should be able to call `client.call("ExtendSession")...` like so:

```python
credentials = Credentials(username=..., database=..., server=..., session_id=...)
client = API.from_credentials(credentials)
client.call('ExtendSession', database=..., userName=..., sessionId=...)

# Make calls here
client.get('User', ....)
```

Please let me know if that worked for you
