### ISSUE TITLE
query API get 'Driver'  borks in api.py - InvalidCastException Geotab.Checkmate.Database.Bridge.UserBridge

### ISSUE THREAD

**Issue by mcallaghan-bsm** [Geotab/mygeotab-python#221]
New user for mygeotab python package.  Recently installed it, and walking through some basics.

Environment:
 * setup a simple NEW database in mygeotab
 * populated with a few users (an admin, and a regular user that is also a driver)

As per: https://mygeotab-python.readthedocs.io/en/latest/

Let's start with a simple example that works:

I'm authenticating like this:
``` python
import mygeotab as gt

client = gt.API(username='email@domain.com', password='strong_password', database='my_db_name')
client.authenticate()
```

That seems to work.

And so do a few examples:
``` python
users = client.get('User')
print(users)
```
, run that and we get real output, formatted as `JSON`. kk

Let's confirm we get three users (matches my DB stage)
``` python
users = client.get('User')
for user in users:
    print(user)
```
, run it:
``` bash
$ python3.7 main.py  | wc -l
3
```
== OK

Can also do stuff such as filtering by name, etc. (tested out a few, those work).  Good baseline.  Moving on.

----
Let's now try what is **_BROKEN_**.  Querying for drivers.
``` python
drivers = client.get('Driver')
print(drivers)
```

As with the "get me all users", I expect the same to work for driver, "get me all drivers"
https://geotab.github.io/sdk/software/api/reference/#T:Geotab.Checkmate.ObjectModel.Driver

kaboom!
``` python
$ python3.7 main.py 
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    drivers = client.get('Driver')
  File "/usr/local/lib/python3.7/dist-packages/mygeotab/api.py", line 144, in get
    return self.call('Get', type_name=type_name, **parameters)
  File "/usr/local/lib/python3.7/dist-packages/mygeotab/api.py", line 96, in call
    result = _query(self._server, method, params, self.timeout, verify_ssl=self._is_verify_ssl)
  File "/usr/local/lib/python3.7/dist-packages/mygeotab/api.py", line 315, in _query
    return _process(response.json(object_hook=object_deserializer))
  File "/usr/local/lib/python3.7/dist-packages/mygeotab/api.py", line 327, in _process
    raise MyGeotabException(data['error'])
mygeotab.exceptions.MyGeotabException: InvalidCastException
Unable to cast object of type \u0027Geotab.Checkmate.Database.Bridge.UserBridge\u0027 to type \u0027Geotab.Database.IGetStore\u00601[Geotab.Checkmate.ObjectModel.Driver]\u0027.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    drivers = client.get('Driver')
  File "/usr/local/lib/python3.7/dist-packages/mygeotab/api.py", line 144, in get
    return self.call('Get', type_name=type_name, **parameters)
  File "/usr/local/lib/python3.7/dist-packages/mygeotab/api.py", line 96, in call
    result = _query(self._server, method, params, self.timeout, verify_ssl=self._is_verify_ssl)
  File "/usr/local/lib/python3.7/dist-packages/mygeotab/api.py", line 315, in _query
    return _process(response.json(object_hook=object_deserializer))
  File "/usr/local/lib/python3.7/dist-packages/mygeotab/api.py", line 327, in _process
    raise MyGeotabException(data['error'])
mygeotab.exceptions.MyGeotabException: InvalidCastException
Unable to cast object of type \u0027Geotab.Checkmate.Database.Bridge.UserBridge\u0027 to type \u0027Geotab.Database.IGetStore\u00601[Geotab.Checkmate.ObjectModel.Driver]\u0027.
```

Tracing through the code a bit to confirm ..

Indeed we hit this last line in _query()
https://github.com/Geotab/mygeotab-python/blob/master/mygeotab/api.py#L318
``` python
 return _process(response.json(object_hook=object_deserializer))
```

Then I suppose we confirm we got "some data", but the API returned an error.
https://github.com/Geotab/mygeotab-python/blob/master/mygeotab/api.py#L329
``` python
    if data:
        if 'error' in data:
            raise MyGeotabException(data['error'])   <<<<
        if 'result' in data:
            return data['result']
return data
```

So the exception itself comes from
https://github.com/Geotab/mygeotab-python/blob/master/mygeotab/exceptions.py#L10
This is passing on the error from the API call.

Which we can see is:
``` python
mygeotab.exceptions.MyGeotabException: InvalidCastException
Unable to cast object of type \u0027Geotab.Checkmate.Database.Bridge.UserBridge\u0027 to type \u0027Geotab.Database.IGetStore\u00601[Geotab.Checkmate.ObjectModel.Driver]\u0027.
```

At this point there's nothing else for me to debug ... the API is tossing an error back to us.  So submitting this issue. (though perhaps we may argue that there's no issue specifically with `mygeotab` package ... please advise if there's a more proper issue submission place for the API itself rather than the python `mygeotab` package).

Tried some online searches, and a few users have reported errors/issues along these lines, but probably not exactly the same.
 * https://helpdesk.geotab.com/hc/en-us/community/posts/360002506243-Getting-InvalidCastException-sometimes-when-calling-API-that-returns-a-list
 * etc (DDG/google search it)

_Specifically_ I've found this one report that matches exactly the error (though for a different use/scenario)
 * https://helpdesk.geotab.com/hc/en-us/community/posts/115011530926-DriverGroups-when-add-User

**Comment by aaront** [comment]
Hey Matt, it's not broken. Querying for Drivers is done though "User". So, you'd use a [UserSearch](https://geotab.github.io/sdk/software/api/reference/#T:Geotab.Checkmate.ObjectModel.UserSearch) in the query.

So, to get only `Driver`s from the DB:

`drivers = client.get('User', isDriver=True)`

Also, when you do a `users = client.get('User')` call, the Driver-based properties (driverGroups, keys, etc.) are included for those Users that are also Drivers.

**Comment by mcallaghan-bsm** [comment]
Thanks Aaron. Indeed it seems true that the concept of a driver _does not_ have a unique entity, but rather is tied to a user via state/fields.

The SDK documentation implies (misleads) that the `Driver` entity can be queried via `get`.

**Comment by mcallaghan-bsm** [comment]
Anyhow, since this definitely is not an issue specific to mygeotab-python, I have deferred into
https://helpdesk.geotab.com/hc/en-us/community/posts/360043469572-SDK-API-Reference-implies-Get-can-operate-on-a-Driver-entity
