### ISSUE TITLE
client.get('ExceptionEvent') returning UnknownDriverId

### ISSUE THREAD

**Issue by bneelon85** [Geotab/mygeotab-python#260]
I am using the Python 'mygeotab' sdk for an ETL job, and it has been working great until I realized today it was broken(based on the data, somewhere around July 10th).

I authenticate just fine and then make the call `events = client.get('ExceptionEvent')`. This works as well, but the driver field in the response is returning `UnkownDriverID` whereas before it was returning a dictionary/object with 3 keys.

I'm wondering if this is an SDK issue or if it's a database issue. My gut tells the the latter because the other fields look correct. However, I called GeoTab support and they couldn't find anything to indicate that something had changed on the database end. Any help would be greatly appreciated.
![image](https://user-images.githubusercontent.com/12244629/61551329-79274880-aa1a-11e9-899c-f7837657e738.png)

**Comment by aaront** [comment]
Closing this off, sorry for the late response.

If the Driver is unknown for an ExceptionEvent object, we return the string "UnknownDriverId" per the API contract: https://geotab.github.io/sdk/software/api/reference/#T:Geotab.Checkmate.ObjectModel.Driver

Maybe up to now these events had drivers associated?
