### ISSUE TITLE
runtime error: AttributeError: module 'arrow.factory' has no attribute 'ArrowParseWarning'

### ISSUE THREAD

**Issue by dxp168** [Geotab/mygeotab-python#311]
arrow==0.14.7 is required by mygeotab==0.8.4
When deploying to AWS without arrow==0.14.7 in the requirement.txt, an older release of arrow is selected by default. This will cause: "AttributeError: module 'arrow.factory' has no attribute 'ArrowParseWarning'"

**Comment by aaront** [comment]
Hey @dxp168 I'll be publishing 0.8.5 today to fix the issue found in #306

**Comment by aaront** [comment]
Published
