### ISSUE TITLE
Patch LogRecords that have dates instead of datetimes

### ISSUE THREAD

**Issue by nathanielobrown** [Geotab/mygeotab-python#325]
If a `LogRecord` occurs at midnight UTC Geotab returns a date rather than a datetime, see [this issue](https://helpdesk.geotab.com/hc/en-us/community/posts/214460783-LogRecord-DateTime-format). When using rapidjson for parsing this date is not converted to a datetime. It works without rapidjson, but then parsing is way too slow.

I'd say this is a failing of the Geotab API, but perhaps we can patch this case in this library? It's not great that the parsing method changes the results, and I can't imagine anyone wanting this behavior.

**Examples**
When using `rapidjson` for JSON deserialization with `rapidjson.DM_ISO8601` 
```
{'dateTime': datetime.date(2019, 10, 31),
 'device': {'id': 'b9'},
 'id': 'b4ABF6F4',
 'latitude': 33.8050041,
 'longitude': -118.224411,
 'speed': 17.0}
```
and without `rapidjson.DM_ISO8601`
```
 {'dateTime': '2019-10-31',
  'device': {'id': 'b9'},
  'id': 'b4ABF6F4',
  'latitude': 33.8050041,
  'longitude': -118.224411,
  'speed': 17.0}
```
and without rapidjson
```
{'dateTime': datetime.datetime(2019, 10, 31, 0, 0, tzinfo=<UTC>),
 'device': {'id': 'b9'},
 'id': 'b4ABF6F4',
 'latitude': 33.8050041,
 'longitude': -118.224411,
 'speed': 17.0}
```
I've patched this in my application, but I thought I would document here. If the maintainers agree on patching this, I could also write the patch.

**Comment by aaront** [comment]
Hey @nathanielobrown I'll take a look, however, the 1903 release that's currently being rolled out in stages now will now return all dates in ISO 8601 format (see [the 1903 release notes here](https://www.geotab.com/blog/mygeotab-updates-1903/)).

**Comment by nathanielobrown** [comment]
Good! Well that's the real fix... Any idea when that will be completely rolled out?

I say we don't fix this if that is the case.

**Comment by aaront** [comment]
Roll-out on the server side is complete. Closing.
