### ISSUE TITLE
Unable to authenticate api connection

### ISSUE THREAD

**Issue by lo-ise** [Geotab/mygeotab-python#91]
Hi @aaront, 

I've been trying to use this module to connect to our Geotab account, however I have encountered the following error when running:

```
>>> api = mygeotab.api(username='***', password='***', database='****', server='****')
>>> api.authenticate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/mygeotab/api.py", line 192, in authenticate
    verify_ssl=self._is_verify_ssl)
  File "/usr/local/lib/python2.7/site-packages/mygeotab/api.py", line 299, in _query
    session.mount('https://', GeotabHTTPAdapter())
  File "/Users/Ireland/.qgis2/python/plugins/opengeo/ext-libs/requests-2.0.1-py2.7.egg/requests/adapters.py", line 84, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "/usr/local/lib/python2.7/site-packages/mygeotab/api.py", line 271, in init_poolmanager
    ssl_version=ssl.PROTOCOL_TLSv1_2,
AttributeError: 'module' object has no attribute 'PROTOCOL_TLSv1_2'
```

Note, I have used '***' instead of our actual credentials. 

Are you able to give me some pointers on what might be going wrong here? Let me know if you need more details?

With many thanks

**Comment by aaront** [comment]
Hi @lo-ise,

Which Python version are you running?

You can find this by running ``python --version`` in your terminal.

MyGeotab servers require TLS 1.2 when making requests, which is only available in Python 2.7+ or Python 3.4+.

**Comment by lo-ise** [comment]
Hi @aaront 

Thanks for your quick response. I was using 2.7.8. I've just tried with Python 3.4.2 and I get the same error. 

I also just tried within a Python3 virtualenv, so therefore I ran `pip install mygeotab` again. I noticed the following error when pip installing:

```
*** Error compiling '/Users/Ireland/python_training/geotab/venv/build/mygeotab/mygeotab/async/api.py'...
  File "/Users/Ireland/python_training/geotab/venv/build/mygeotab/mygeotab/async/api.py", line 49
    async def call_async(self, method, **parameters):
            ^
SyntaxError: invalid syntax

Successfully installed mygeotab python-dateutil six click pytz requests urllib3 idna certifi chardet
Cleaning up...
```

Is this helpful/related?

With many thanks for your help!

**Comment by aaront** [comment]
Hey @lo-ise,

Sorry for the delayed response. "PROTOCOL_TLSv1_2" is actually only supported in Python 2.7.9 and above.

As for Python 3.4, that error can be ignored. It still installs the package, as expected. Just doesn't understand the new syntax for asynchronous code that was introduced in Python 3.5. The package should still work.

**Comment by lo-ise** [comment]
Hey @aaront 

Apologies for really slow response. We've just started working on this again after a short break. Just to say we have it all working now so massive thank you for your help!
