### ISSUE TITLE
When did you commit v0.9.0?

### ISSUE THREAD

**Issue by 3BK** [Geotab/mygeotab-python#98]
Your documentation and git hub don't appear to be in sync.
When did you commit 0.9.0?  
As of today, 240216, the latest github tag is v0.8.8.
That said, your documentation claims you commited v0.9.0 on 240208.

https://github.com/Geotab/mygeotab-python
https://mygeotab-python.readthedocs.io/en/latest/#id1

**Comment by aaront** [comment]
Hi @3BK, I haven't tagged a new release yet. Will do so shortly.

**Comment by 3BK** [comment]
[like]  Brent Kimberley reacted to your message:
________________________________
